name: Android CI

on:
  push:
    branches: [ "ci/cd"]
  pull_request:
    branches: [ "ci/cd"]

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
      - name: Build app
        run: chmod +x gradlew
